language: cpp
compiler:
    - gcc
script: cmake ./Source && make
after_script: ./QCoreUnitTest/QCoreUnitTest < ./Tools/input.txt
notifications:
    recipients:
        - lwch748@gmail.com
    email:
        on_success: change
        on_failure: always
